# Nixpacks Configuration for Railway
# Force rebuild - Updated Oct 7, 2025 v2

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mongodb", "php82Extensions.pdo_mysql", "nodejs_18", "php82Packages.composer"]

[phases.install]
cmds = ["npm ci", "composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-mongodb"]

[phases.build]  
cmds = ["npm run build"]
