# Nixpacks Configuration for Railway# Nixpacks Configuration for Railway

# Minimal config - let Procfile handle start command# Force rebuild - Updated Oct 15, 2025



[phases.setup][phases.setup]

nixPkgs = ["php82", "php82Extensions.mongodb", "php82Extensions.pdo_mysql", "nodejs_18", "php82Packages.composer"]nixPkgs = ["php82", "php82Extensions.mongodb", "php82Extensions.pdo_mysql", "nodejs_18", "php82Packages.composer"]



[phases.install][phases.install]

cmds = ["npm ci", "composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-mongodb"]cmds = ["npm ci", "composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-mongodb"]



[phases.build][phases.build]  

cmds = ["npm run build"]cmds = ["npm run build"]


# No [start] section - let Railway use Procfile instead
