# Nixpacks Configuration for Railway
# This file tells Railway how to install PHP extensions

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mongodb", "php82Extensions.pdo_mysql", "nodejs_18", "php82Packages.composer"]

[phases.install]
cmds = ["npm ci", "composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-mongodb"]

[phases.build]  
cmds = ["npm run build"]

[phases.deploy]
cmds = ["bash .railway/deploy.sh"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"