# Nixpacks Configuration for Railway
# This file tells Railway how to install PHP extensions
# Updated to include MongoDB seeder

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mongodb", "php82Extensions.pdo_mysql", "nodejs_18", "php82Packages.composer"]

[phases.install]
cmds = ["npm ci", "composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-mongodb"]

[phases.build]  
cmds = ["npm run build"]

[start]
cmd = "bash railway-start.sh"