# Nixpacks Configuration for Railway
# Minimal config - let Procfile handle start command

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mongodb", "php82Extensions.pdo_mysql", "nodejs_18", "php82Packages.composer"]

[phases.install]
cmds = ["npm ci", "composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-mongodb"]

[phases.build]
cmds = ["npm run build"]
# No [start] section - let Railway use Procfile instead
